### ISSUE TITLE
policies.get_by_name("Fixed Default Backup Policy") 

### ISSUE THREAD

**Issue by svt-kmcdaniel** [HewlettPackard/simplivity-python-sdk#10]
policies.get_by_name("Fixed Default Backup Policy") raises a json.decoder.JSONDecodeError due to invalid url encoding.

`Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    policies.get_by_name("Fixed Default Backup Policy")
  File "/home/kmcdaniel/bitbucket/simplivity-python/simplivity/resources/resource.py", line 307, in get_by_name
    resources = self.get_all(filters={'name': name})
  File "/home/kmcdaniel/bitbucket/simplivity-python/simplivity/resources/policies.py", line 63, in get_all
    case_sensitive=case_sensitive)
  File "/home/kmcdaniel/bitbucket/simplivity-python/simplivity/resources/resource.py", line 196, in get_all
    response = self._connection.get(url)
  File "/home/kmcdaniel/bitbucket/simplivity-python/simplivity/connection.py", line 130, in get
    resp, body = self.do_http('GET', url, '')
  File "/home/kmcdaniel/bitbucket/simplivity-python/simplivity/connection.py", line 87, in do_http
    body = json.loads(response.decode('utf-8'))
  File "/home/kmcdaniel/.pyenv/versions/3.7.3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/kmcdaniel/.pyenv/versions/3.7.3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/kmcdaniel/.pyenv/versions/3.7.3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by svt-kmcdaniel** [comment]
This issue is resolved by encoding the query params dictionary into a query string using urllib.parse.urlencode ( see PR #11 )
